# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eUagOlwIn2PpXyZOyba26fr8JUk9bCgR
"""

import streamlit as st
import joblib
import pandas as pd
import json

# Load the saved model and scaler
model = joblib.load('parkinsons_model.pkl')
scaler = joblib.load('scaler.pkl')

st.set_page_config(page_title="Parkinson's AI Diagnostic", layout="centered")

st.title("🧠 Parkinson's Disease Detection")
st.write("Upload a **.json** file with voice features for an AI-powered diagnosis.")

# File uploader
uploaded_file = st.file_uploader("Choose a JSON file", type="json")

if uploaded_file is not None:
    data = json.load(uploaded_file)
    df_input = pd.DataFrame([data])

    st.subheader("Data Preview")
    st.write(df_input)

    if st.button("Run Diagnostic"):
        # Scale the data using the exported scaler
        scaled_data = scaler.transform(df_input.values)

        # Predict using the exported SVM model
        prediction = model.predict(scaled_data)

        st.divider()
        if prediction[0] == 1:
            st.error("### Result: Parkinson's Disease Detected")
        else:
            st.success("### Result: Healthy / No Parkinson's Detected")

